"""new fields in user model

Revision ID: 867709bcaae5
Revises: bafc1b5c4420
Create Date: 2021-12-29 19:55:44.794110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867709bcaae5'
down_revision = 'bafc1b5c4420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
